In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pld
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [23]:
df = pd.read_csv("data\OnlineNewsPopularity.csv")
df.columns=df.columns.str.replace(' ','')
df["popularity"]=df['shares'].apply(lambda x:0 if x<1400 else 1)
X = df.drop(['url','timedelta','shares','popularity'], axis=1)
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)


In [27]:
lg = LogisticRegression()
logsticModel = lg.fit(X_train, y_train)
y_predict = lg.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)


Confusion Matrix:
[[2551 3034]
 [1885 4424]]
Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.46      0.51      5585
           1       0.59      0.70      0.64      6309

    accuracy                           0.59     11894
   macro avg       0.58      0.58      0.58     11894
weighted avg       0.58      0.59      0.58     11894

Accuracy: 0.5864301328400875


C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [38]:
X=df[['n_tokens_title','n_tokens_content','data_channel_is_lifestyle','data_channel_is_bus','data_channel_is_entertainment','data_channel_is_socmed','data_channel_is_tech','data_channel_is_world',"num_imgs",'num_videos',
     'weekday_is_monday','weekday_is_tuesday','weekday_is_wednesday','weekday_is_thursday','weekday_is_friday','weekday_is_saturday','weekday_is_sunday']]

y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)
lg = LogisticRegression()
logsticModel = lg.fit(X_train, y_train)
y_predict = lg.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)

Confusion Matrix:
[[2963 2622]
 [1820 4489]]
Classification Report:
              precision    recall  f1-score   support

           0       0.62      0.53      0.57      5585
           1       0.63      0.71      0.67      6309

    accuracy                           0.63     11894
   macro avg       0.63      0.62      0.62     11894
weighted avg       0.63      0.63      0.62     11894

Accuracy: 0.6265343870859257


C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [46]:
X=df[['n_tokens_title','n_tokens_content','data_channel_is_lifestyle','data_channel_is_bus','data_channel_is_entertainment','data_channel_is_socmed','data_channel_is_tech','data_channel_is_world',"num_imgs",'num_videos',
     'weekday_is_monday','weekday_is_tuesday','weekday_is_wednesday','weekday_is_thursday','weekday_is_friday','weekday_is_saturday','weekday_is_sunday','global_rate_positive_words','global_rate_negative_words',
     'LDA_00','LDA_01','LDA_02','LDA_03','LDA_04']]

y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)
lg = LogisticRegression()
logsticModel = lg.fit(X_train, y_train)
y_predict = lg.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)

Confusion Matrix:
[[2905 2680]
 [1747 4562]]
Classification Report:
              precision    recall  f1-score   support

           0       0.62      0.52      0.57      5585
           1       0.63      0.72      0.67      6309

    accuracy                           0.63     11894
   macro avg       0.63      0.62      0.62     11894
weighted avg       0.63      0.63      0.62     11894

Accuracy: 0.6277955271565495


C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
