In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pld
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [48]:
df = pd.read_csv("data\OnlineNewsPopularity.csv")
df.columns=df.columns.str.replace(' ','')
df["popularity"]=df['shares'].apply(lambda x:0 if x<1400 else 1)
X = df.drop(['url','timedelta','shares','popularity'], axis=1)
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)


In [49]:
nb = GaussianNB()
NaiveBayesModel = nb.fit(X_train, y_train)
y_predict = nb.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)

Confusion Matrix:
[[5036  549]
 [5062 1247]]
Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.90      0.64      5585
           1       0.69      0.20      0.31      6309

    accuracy                           0.53     11894
   macro avg       0.60      0.55      0.47     11894
weighted avg       0.60      0.53      0.46     11894

Accuracy: 0.5282495375819741


In [50]:
X=df[['n_tokens_title','n_tokens_content','data_channel_is_lifestyle','data_channel_is_bus','data_channel_is_entertainment','data_channel_is_socmed','data_channel_is_tech','data_channel_is_world',"num_imgs",'num_videos',
     'weekday_is_monday','weekday_is_tuesday','weekday_is_wednesday','weekday_is_thursday','weekday_is_friday','weekday_is_saturday','weekday_is_sunday']]
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)


nb = GaussianNB()
NaiveBayesModel = nb.fit(X_train, y_train)
y_predict = nb.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)

Confusion Matrix:
[[4229 1356]
 [3586 2723]]
Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.76      0.63      5585
           1       0.67      0.43      0.52      6309

    accuracy                           0.58     11894
   macro avg       0.60      0.59      0.58     11894
weighted avg       0.61      0.58      0.57     11894

Accuracy: 0.5844963847317975


In [56]:
X=df[['kw_avg_avg','LDA_03','kw_max_avg','kw_min_avg','num_hrefs','kw_avg_max','global_subjectivity','abs_title_sentiment_polarity','weekday_is_sunday','title_subjectivity']]
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)


nb = GaussianNB()
NaiveBayesModel = nb.fit(X_train, y_train)
y_predict = nb.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)




Confusion Matrix:
[[4306 1279]
 [3929 2380]]
Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.77      0.62      5585
           1       0.65      0.38      0.48      6309

    accuracy                           0.56     11894
   macro avg       0.59      0.57      0.55     11894
weighted avg       0.59      0.56      0.55     11894

Accuracy: 0.5621321674794014


In [58]:
X=df[['n_tokens_title','n_tokens_content','data_channel_is_lifestyle','data_channel_is_bus','data_channel_is_entertainment','data_channel_is_socmed','data_channel_is_tech','data_channel_is_world',"num_imgs",'num_videos',
     'weekday_is_monday','weekday_is_tuesday','weekday_is_wednesday','weekday_is_thursday','weekday_is_friday','weekday_is_saturday','weekday_is_sunday','global_rate_positive_words','global_rate_negative_words',
     'LDA_00','LDA_01','LDA_02','LDA_03','LDA_04','kw_avg_avg','kw_max_avg','kw_min_avg','num_hrefs']]
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)


nb = GaussianNB()
NaiveBayesModel = nb.fit(X_train, y_train)
y_predict = nb.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)

Confusion Matrix:
[[3957 1628]
 [2901 3408]]
Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.71      0.64      5585
           1       0.68      0.54      0.60      6309

    accuracy                           0.62     11894
   macro avg       0.63      0.62      0.62     11894
weighted avg       0.63      0.62      0.62     11894

Accuracy: 0.6192197746763074
