In [5]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
%matplotlib inline

In [6]:
df = pd.read_csv(r'data\OnlineNewsPopularity.csv' , sep=r'\s*,\s*')
df.head()

C:\Users\Mahta\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


url  timedelta  \
0  http://mashable.com/2013/01/07/amazon-instant-...      731.0   
1  http://mashable.com/2013/01/07/ap-samsung-spon...      731.0   
2  http://mashable.com/2013/01/07/apple-40-billio...      731.0   
3  http://mashable.com/2013/01/07/astronaut-notre...      731.0   
4   http://mashable.com/2013/01/07/att-u-verse-apps/      731.0   

   n_tokens_title  n_tokens_content  n_unique_tokens  n_non_stop_words  \
0            12.0             219.0         0.663594               1.0   
1             9.0             255.0         0.604743               1.0   
2             9.0             211.0         0.575130               1.0   
3             9.0             531.0         0.503788               1.0   
4            13.0            1072.0         0.415646               1.0   

   n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  num_imgs  ...  \
0                  0.815385        4.0             2.0       1.0  ...   
1                  0.791946        3.0             1.0       1.0  ...   
2                  0.663866        3.0             1.0       1.0  ...   
3                  0.665635        9.0             0.0       1.0  ...   
4                  0.540890       19.0            19.0      20.0  ...   

   min_positive_polarity  max_positive_polarity  avg_negative_polarity  \
0               0.100000                    0.7              -0.350000   
1               0.033333                    0.7              -0.118750   
2               0.100000                    1.0              -0.466667   
3               0.136364                    0.8              -0.369697   
4               0.033333                    1.0              -0.220192   

   min_negative_polarity  max_negative_polarity  title_subjectivity  \
0                 -0.600              -0.200000            0.500000   
1                 -0.125              -0.100000            0.000000   
2                 -0.800              -0.133333            0.000000   
3                 -0.600              -0.166667            0.000000   
4                 -0.500              -0.050000            0.454545   

   title_sentiment_polarity  abs_title_subjectivity  \
0                 -0.187500                0.000000   
1                  0.000000                0.500000   
2                  0.000000                0.500000   
3                  0.000000                0.500000   
4                  0.136364                0.045455   

   abs_title_sentiment_polarity  shares  
0                      0.187500     593  
1                      0.000000     711  
2                      0.000000    1500  
3                      0.000000    1200  
4                      0.136364     505  

[5 rows x 61 columns]

In [7]:
cdf = df[["global_subjectivity","rate_positive_words","rate_negative_words",
     "avg_positive_polarity","min_positive_polarity","max_positive_polarity","avg_negative_polarity","min_negative_polarity",
     "max_negative_polarity","title_subjectivity","abs_title_sentiment_polarity","shares","data_channel_is_lifestyle","data_channel_is_entertainment","data_channel_is_bus",
      "data_channel_is_socmed","data_channel_is_tech","data_channel_is_world",
     "weekday_is_monday","weekday_is_tuesday","weekday_is_wednesday","weekday_is_thursday","weekday_is_friday",
     "weekday_is_saturday","weekday_is_sunday"]]
cdf.head(9)

global_subjectivity  rate_positive_words  rate_negative_words  \
0             0.521617             0.769231             0.230769   
1             0.341246             0.733333             0.266667   
2             0.702222             0.857143             0.142857   
3             0.429850             0.666667             0.333333   
4             0.513502             0.860215             0.139785   
5             0.437409             0.523810             0.476190   
6             0.514480             0.827957             0.172043   
7             0.543474             0.846939             0.153061   
8             0.538889             0.600000             0.400000   

   avg_positive_polarity  min_positive_polarity  max_positive_polarity  \
0               0.378636               0.100000                    0.7   
1               0.286915               0.033333                    0.7   
2               0.495833               0.100000                    1.0   
3               0.385965               0.136364                    0.8   
4               0.411127               0.033333                    1.0   
5               0.350610               0.136364                    0.6   
6               0.402039               0.100000                    1.0   
7               0.427720               0.100000                    1.0   
8               0.566667               0.400000                    0.8   

   avg_negative_polarity  min_negative_polarity  max_negative_polarity  \
0              -0.350000                 -0.600              -0.200000   
1              -0.118750                 -0.125              -0.100000   
2              -0.466667                 -0.800              -0.133333   
3              -0.369697                 -0.600              -0.166667   
4              -0.220192                 -0.500              -0.050000   
5              -0.195000                 -0.400              -0.100000   
6              -0.224479                 -0.500              -0.050000   
7              -0.242778                 -0.500              -0.050000   
8              -0.125000                 -0.125              -0.125000   

   title_subjectivity  ...  data_channel_is_socmed  data_channel_is_tech  \
0            0.500000  ...                     0.0                   0.0   
1            0.000000  ...                     0.0                   0.0   
2            0.000000  ...                     0.0                   0.0   
3            0.000000  ...                     0.0                   0.0   
4            0.454545  ...                     0.0                   1.0   
5            0.642857  ...                     0.0                   1.0   
6            0.000000  ...                     0.0                   0.0   
7            1.000000  ...                     0.0                   1.0   
8            0.125000  ...                     0.0                   1.0   

   data_channel_is_world  weekday_is_monday  weekday_is_tuesday  \
0                    0.0                1.0                 0.0   
1                    0.0                1.0                 0.0   
2                    0.0                1.0                 0.0   
3                    0.0                1.0                 0.0   
4                    0.0                1.0                 0.0   
5                    0.0                1.0                 0.0   
6                    0.0                1.0                 0.0   
7                    0.0                1.0                 0.0   
8                    0.0                1.0                 0.0   

   weekday_is_wednesday  weekday_is_thursday  weekday_is_friday  \
0                   0.0                  0.0                0.0   
1                   0.0                  0.0                0.0   
2                   0.0                  0.0                0.0   
3                   0.0                  0.0                0.0   
4                   0.0                  0.0                0.0   
5     

In [8]:
msk = np.random.rand(len(df)) < 0.8
train = cdf[msk]
test = cdf[~msk]

In [9]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
train_x = np.asanyarray(train[["global_subjectivity","rate_positive_words","rate_negative_words",
     "avg_positive_polarity","min_positive_polarity","max_positive_polarity","avg_negative_polarity","min_negative_polarity",
     "max_negative_polarity","title_subjectivity","abs_title_sentiment_polarity","data_channel_is_lifestyle","data_channel_is_entertainment","data_channel_is_bus",
      "data_channel_is_socmed","data_channel_is_tech","data_channel_is_world",
     "weekday_is_monday","weekday_is_tuesday","weekday_is_wednesday","weekday_is_thursday","weekday_is_friday",
     "weekday_is_saturday","weekday_is_sunday"]])
train_y = np.asanyarray(train[["shares"]])

test_x = np.asanyarray(test[["global_subjectivity","rate_positive_words","rate_negative_words",
     "avg_positive_polarity","min_positive_polarity","max_positive_polarity","avg_negative_polarity","min_negative_polarity",
     "max_negative_polarity","title_subjectivity","abs_title_sentiment_polarity","data_channel_is_lifestyle","data_channel_is_entertainment","data_channel_is_bus",
      "data_channel_is_socmed","data_channel_is_tech","data_channel_is_world",
     "weekday_is_monday","weekday_is_tuesday","weekday_is_wednesday","weekday_is_thursday","weekday_is_friday",
     "weekday_is_saturday","weekday_is_sunday"]])
test_y = np.asanyarray(test[["shares"]])


poly = PolynomialFeatures(degree=2)
train_x_poly = poly.fit_transform(train_x)
train_x_poly

array([[1.        , 0.52161715, 0.76923077, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.34124579, 0.73333333, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.70222222, 0.85714286, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.56437426, 0.8125    , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.51029582, 0.57692308, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.51789322, 0.83333333, ..., 0.        , 0.        ,
        0.        ]])

In [10]:
clf = linear_model.LinearRegression()
train_y_ = clf.fit(train_x_poly, train_y)
# The coefficients
print ('Coefficients: ', clf.coef_)
print ('Intercept: ',clf.intercept_)

Coefficients:  [[ 2.02522162e+10 -1.71220307e+15  3.35001388e+15  3.73841401e+15
   8.95298564e+15 -2.81628783e+16  6.65621212e+15  3.78386523e+16
  -1.55574314e+16 -1.57054566e+16  3.00081487e+15  7.28811930e+14
   8.50070581e+14 -1.10757007e+16 -1.18337985e+15 -3.86744097e+14
   5.98430250e+15  9.72728526e+15 -1.47483956e+16 -6.20332773e+16
   2.40256816e+15 -1.19737554e+16 -1.27466542e+16 -6.14936304e+15
  -8.36307971e+15 -5.50550000e+03  1.30115000e+04  7.76875000e+03
  -1.49721875e+03  6.61906250e+03 -1.40062500e+03 -2.23122500e+04
   5.66950000e+03  2.73537500e+03 -1.54000000e+02  5.33350000e+03
   2.55250000e+03  3.49500000e+03  5.88450000e+03 -1.50462500e+03
   8.51000000e+02  4.51775000e+03  1.71220307e+15  1.71220307e+15
   1.71220307e+15  1.71220307e+15  1.71220307e+15  1.71220307e+15
   1.71220307e+15 -9.22797227e+15 -1.23254291e+16 -4.84382839e+15
   3.76173410e+16  7.57906017e+15 -4.11308929e+16  2.17191733e+16
   1.57751687e+16 -6.85000000e+02 -1.00850000e+03 -3.43675000

In [11]:
from sklearn.metrics import r2_score

test_x_poly = poly.fit_transform(test_x)
test_y_ = clf.predict(test_x_poly)

print("Mean absolute error: %.2f" % np.mean(np.absolute(test_y_ - test_y)))
print("Residual sum of squares (MSE): %.2f" % np.mean((test_y_ - test_y) ** 2))
print("R2-score: %.2f" % r2_score(test_y_ , test_y) )

Mean absolute error: 3183.89
Residual sum of squares (MSE): 149786633.39
R2-score: -51.82


In [17]:
result = confusion_matrix(test_y, test_y_)
print("Confusion Matrix:")
print(result)
result1 = classification_report(test_y, test_y_)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(test_y,test_y_)
print("Accuracy:",result2)

Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
              precision    recall  f1-score   support

     -4092.0       0.00      0.00      0.00         0
     -3232.0       0.00      0.00      0.00         0
     -3218.0       0.00      0.00      0.00         0
     -2092.0       0.00      0.00      0.00         0
     -2004.0       0.00      0.00      0.00         0
     -1296.0       0.00      0.00      0.00         0
     -1064.0       0.00      0.00      0.00         0
      -808.0       0.00      0.00      0.00         0
      -736.0       0.00      0.00      0.00         0
      -660.0       0.00      0.00      0.00         0
      -494.0       0.00      0.00      0.00         0
      -466.0       0.00      0.00      0.00         0
      -432.0       0.00      0.00      0.00         0
      -412.0       0.00      0.00      0.00         0
      -386.0       0.00     

C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
