In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pld
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [61]:
df = pd.read_csv("data\OnlineNewsPopularity.csv")
df.columns=df.columns.str.replace(' ','')
df["popularity"]=df['shares'].apply(lambda x:0 if x<1400 else 1)
X = df.drop(['url','timedelta','shares','popularity'], axis=1)
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)


In [72]:
supportVectorMachine = svm.LinearSVC()
svmModel = supportVectorMachine.fit(X_train, y_train)
y_predict = supportVectorMachine.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)


Confusion Matrix:
[[5171  414]
 [5694  615]]
Classification Report:
              precision    recall  f1-score   support

           0       0.48      0.93      0.63      5585
           1       0.60      0.10      0.17      6309

    accuracy                           0.49     11894
   macro avg       0.54      0.51      0.40     11894
weighted avg       0.54      0.49      0.38     11894

Accuracy: 0.4864637632419707


C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [67]:
X=df[['n_tokens_title','n_tokens_content','data_channel_is_lifestyle','data_channel_is_bus','data_channel_is_entertainment','data_channel_is_socmed','data_channel_is_tech','data_channel_is_world',"num_imgs",'num_videos',
     'weekday_is_monday','weekday_is_tuesday','weekday_is_wednesday','weekday_is_thursday','weekday_is_friday','weekday_is_saturday','weekday_is_sunday']]
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)
supportVectorMachine = svm.LinearSVC()
svmModel = supportVectorMachine.fit(X_train, y_train)
y_predict = supportVectorMachine.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)


Confusion Matrix:
[[5430  155]
 [6040  269]]
Classification Report:
              precision    recall  f1-score   support

           0       0.47      0.97      0.64      5585
           1       0.63      0.04      0.08      6309

    accuracy                           0.48     11894
   macro avg       0.55      0.51      0.36     11894
weighted avg       0.56      0.48      0.34     11894

Accuracy: 0.47914915083235243


C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [68]:
X=df[['n_tokens_title','n_tokens_content','data_channel_is_lifestyle','data_channel_is_bus','data_channel_is_entertainment','data_channel_is_socmed','data_channel_is_tech','data_channel_is_world',"num_imgs",'num_videos',
     'weekday_is_monday','weekday_is_tuesday','weekday_is_wednesday','weekday_is_thursday','weekday_is_friday','weekday_is_saturday','weekday_is_sunday','global_rate_positive_words','global_rate_negative_words',
     'LDA_00','LDA_01','LDA_02','LDA_03','LDA_04']]
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)
supportVectorMachine = svm.LinearSVC()
svmModel = supportVectorMachine.fit(X_train, y_train)
y_predict = supportVectorMachine.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)


Confusion Matrix:
[[5498   87]
 [6153  156]]
Classification Report:
              precision    recall  f1-score   support

           0       0.47      0.98      0.64      5585
           1       0.64      0.02      0.05      6309

    accuracy                           0.48     11894
   macro avg       0.56      0.50      0.34     11894
weighted avg       0.56      0.48      0.32     11894

Accuracy: 0.47536573062048093


C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [69]:
X=df[['kw_avg_avg','LDA_03','kw_max_avg','kw_min_avg','num_hrefs','kw_avg_max','global_subjectivity','abs_title_sentiment_polarity','weekday_is_sunday','title_subjectivity']]
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)
supportVectorMachine = svm.LinearSVC()
svmModel = supportVectorMachine.fit(X_train, y_train)
y_predict = supportVectorMachine.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)

Confusion Matrix:
[[5131  454]
 [5542  767]]
Classification Report:
              precision    recall  f1-score   support

           0       0.48      0.92      0.63      5585
           1       0.63      0.12      0.20      6309

    accuracy                           0.50     11894
   macro avg       0.55      0.52      0.42     11894
weighted avg       0.56      0.50      0.40     11894

Accuracy: 0.49588027576929544


C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [75]:
X=df[['kw_avg_avg','LDA_03','kw_max_avg','kw_min_avg','num_hrefs','kw_avg_max','global_subjectivity','abs_title_sentiment_polarity','weekday_is_sunday','title_subjectivity']]
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)
supportVectorMachine = svm.LinearSVC(C=3)
svmModel = supportVectorMachine.fit(X_train, y_train)
y_predict = supportVectorMachine.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)

Confusion Matrix:
[[  48 5537]
 [  61 6248]]
Classification Report:
              precision    recall  f1-score   support

           0       0.44      0.01      0.02      5585
           1       0.53      0.99      0.69      6309

    accuracy                           0.53     11894
   macro avg       0.49      0.50      0.35     11894
weighted avg       0.49      0.53      0.37     11894

Accuracy: 0.5293425256431814


C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [80]:
X=df[['kw_avg_avg','LDA_03','kw_max_avg','kw_min_avg','num_hrefs','kw_avg_max','global_subjectivity','abs_title_sentiment_polarity','weekday_is_sunday','title_subjectivity']]
y = df['popularity']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)
supportVectorMachine = svm.LinearSVC(C=4)
svmModel = supportVectorMachine.fit(X_train, y_train)
y_predict = supportVectorMachine.predict(X_test)
result = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_predict)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_predict)
print("Accuracy:",result2)

Confusion Matrix:
[[5493   92]
 [6165  144]]
Classification Report:
              precision    recall  f1-score   support

           0       0.47      0.98      0.64      5585
           1       0.61      0.02      0.04      6309

    accuracy                           0.47     11894
   macro avg       0.54      0.50      0.34     11894
weighted avg       0.54      0.47      0.32     11894

Accuracy: 0.47393643854044054


C:\Users\Mahta\Anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
